# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-03 04:31
from __future__ import unicode_literals

from django.db import migrations
import world.msgs.models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0016_auto_20180925_1735'),
        ('msgs', '0007_inform_read_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=(world.msgs.models.MarkReadMixin, 'comms.msg'),
        ),
    ]
