# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-03 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0031_auto_20180804_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militaryunit',
            name='unit_type',
            field=models.PositiveSmallIntegerField(blank=0, choices=[(0, b'Infantry'), (1, b'Casters'), (2, b'Cavalry'), (3, b'Archers'), (4, b'Longship'), (5, b'Siege Weapon'), (6, b'Corsair'), (8, b'Cog'), (7, b'Dromond')], default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_10_female',
            field=models.CharField(blank=True, default=b'Banished', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_10_male',
            field=models.CharField(blank=True, default=b'Banished', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_1_female',
            field=models.CharField(blank=True, default=b'Lady', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_1_male',
            field=models.CharField(blank=True, default=b'Lord', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_2_female',
            field=models.CharField(blank=True, default=b'Right Hand', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_2_male',
            field=models.CharField(blank=True, default=b'Right Hand', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_3_female',
            field=models.CharField(blank=True, default=b'Highborn Family', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_3_male',
            field=models.CharField(blank=True, default=b'Highborn Family', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_4_female',
            field=models.CharField(blank=True, default=b'Family', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_4_male',
            field=models.CharField(blank=True, default=b'Family', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_5_female',
            field=models.CharField(blank=True, default=b'Highborn Vassals', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_5_male',
            field=models.CharField(blank=True, default=b'Highborn Vassals', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_7_female',
            field=models.CharField(blank=True, default=b'Denizen', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_7_male',
            field=models.CharField(blank=True, default=b'Denizen', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_8_female',
            field=models.CharField(blank=True, default=b'Wanderer', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_8_male',
            field=models.CharField(blank=True, default=b'Wanderer', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_9_female',
            field=models.CharField(blank=True, default=b'Outcast', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank_9_male',
            field=models.CharField(blank=True, default=b'Outcast', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orgunitmodifiers',
            name='unit_type',
            field=models.PositiveSmallIntegerField(blank=0, choices=[(0, b'Infantry'), (1, b'Casters'), (2, b'Cavalry'), (3, b'Archers'), (4, b'Longship'), (5, b'Siege Weapon'), (6, b'Corsair'), (8, b'Cog'), (7, b'Dromond')], default=0),
        ),
        migrations.AlterField(
            model_name='praiseorcondemn',
            name='message',
            field=models.TextField(),
        ),
    ]
