# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-26 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0033_goal_goalupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Credit the Artist'),
        ),
    ]
