# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-26 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0003_auto_20180827_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fashionsnapshot',
            old_name='fame',
            new_name='prestige',
        ),
    ]
